language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/acm/acm_terminal
    - PLATFORMIO_CI_SRC=examples/adk/adk_barcode/adk_barcode.ino
    - PLATFORMIO_CI_SRC=examples/adk/ArduinoBlinkLED/ArduinoBlinkLED.ino
    - PLATFORMIO_CI_SRC=examples/adk/demokit_20/demokit_20.ino
    - PLATFORMIO_CI_SRC=examples/adk/term_test/term_test.ino
    - PLATFORMIO_CI_SRC=examples/adk/term_time/term_time.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/BTHID
    - PLATFORMIO_CI_SRC=examples/Bluetooth/PS3BT/PS3BT.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/PS3Multi/PS3Multi.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/PS3SPP/PS3SPP.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/PS4BT/PS4BT.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/SPP/SPP.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/SPPMulti/SPPMulti.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/Wii/Wii.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/WiiBalanceBoard/WiiBalanceBoard.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/WiiIRCamera/WiiIRCamera.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/WiiMulti/WiiMulti.ino
    - PLATFORMIO_CI_SRC=examples/Bluetooth/WiiUProController/WiiUProController.ino
    - PLATFORMIO_CI_SRC=examples/board_qc/board_qc.ino
    - PLATFORMIO_CI_SRC=examples/cdc_XR21B1411/XR_terminal/XR_terminal.ino
    - PLATFORMIO_CI_SRC=examples/ftdi/USBFTDILoopback
    - PLATFORMIO_CI_SRC=examples/HID/le3dp
    - PLATFORMIO_CI_SRC=examples/HID/scale
    - PLATFORMIO_CI_SRC=examples/HID/USBHID_desc
    - PLATFORMIO_CI_SRC=examples/HID/USBHIDBootKbd/USBHIDBootKbd.ino
    - PLATFORMIO_CI_SRC=examples/HID/USBHIDBootKbdAndMouse/USBHIDBootKbdAndMouse.ino
    - PLATFORMIO_CI_SRC=examples/HID/USBHIDBootMouse/USBHIDBootMouse.ino
    - PLATFORMIO_CI_SRC=examples/HID/USBHIDJoystick
    - PLATFORMIO_CI_SRC=examples/hub_demo
    - PLATFORMIO_CI_SRC=examples/max_LCD/max_LCD.ino
    - PLATFORMIO_CI_SRC=examples/pl2303/pl2303_gprs_terminal/pl2303_gprs_terminal.ino
    - PLATFORMIO_CI_SRC=examples/pl2303/pl2303_gps/pl2303_gps.ino
    - PLATFORMIO_CI_SRC=examples/pl2303/pl2303_tinygps/pl2303_tinygps.ino
    - PLATFORMIO_CI_SRC=examples/pl2303/pl2303_xbee_terminal/pl2303_xbee_terminal.ino
    - PLATFORMIO_CI_SRC=examples/PS3USB/PS3USB.ino
    - PLATFORMIO_CI_SRC=examples/PS4USB/PS4USB.ino
    - PLATFORMIO_CI_SRC=examples/PSBuzz/PSBuzz.ino
#    - PLATFORMIO_CI_SRC=examples/testusbhostFAT/testusbhostFAT.ino
    - PLATFORMIO_CI_SRC=examples/USB_desc
    - PLATFORMIO_CI_SRC=examples/Xbox/XBOXOLD/XBOXOLD.ino
    - PLATFORMIO_CI_SRC=examples/Xbox/XBOXONE/XBOXONE.ino
    - PLATFORMIO_CI_SRC=examples/Xbox/XBOXRECV/XBOXRECV.ino
    - PLATFORMIO_CI_SRC=examples/Xbox/XBOXUSB/XBOXUSB.ino

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

    # Use PlatformIO from development branch
    # @TODO remove this line after 2.0.1 release
    - pip install https://github.com/platformio/platformio/archive/develop.zip

    # Libraries from PlatformIO Library Register
    # http://platformio.org/#!/lib/show/416/TinyGPS
    # http://platformio.org/#!/lib/show/417/SPI4Teensy3
    - platformio lib install 416 417

script:
    - if [[ $PLATFORMIO_CI_SRC == *"WiiIRCamera"* ]]; then sed -i -- 's/#define ENABLE_WII_IR_CAMERA 0/#define ENABLE_WII_IR_CAMERA 1/g' ./settings.h; fi
    - platformio ci --board=uno --board=teensy31 --board=due --lib="."
